spring:
  datasource:
    url: jdbc:mysql://81.69.232.225:3306/gulimall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  application:
    name: coupon
server:
  port: 7000

other:
  user:
    name: "other配置中心1"
    age: 1